[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100

[tool.pytest.ini_options]
markers = [
  "script: Marks tests provided as shell scripts",
  "pulp_deb: pulp_deb tests",
]

[tool.mypy]
strict = true
show_error_codes = true
files = "pulpcore/**/*.py"
namespace_packages = true
explicit_package_bases = true

[[tool.mypy.overrides]]
module = [
  "urllib3.*",
  "pygments.*",
  "click_shell.*",
  "schema.*",
]
ignore_missing_imports = true
